name: agegrid2
channels:
  - conda-forge
dependencies:
  - python=2
  - numpy
  - matplotlib
  - scipy
  - scikit-image
  - pandas
  - xarray
  - netcdf4
  - joblib
  - geopandas
  - healpy
  - pyyaml
  - gmt
  - geopandas
  - cartopy
  - requests
  - ipykernel


