name: agegrid3
channels:
  - conda-forge
dependencies:
  - python=3
  - numpy
  - matplotlib
  - scipy
  - scikit-image
  - pandas
  - xarray
  - netcdf4
  - joblib
  - geopandas
  - healpy
  - pyyaml
  - gmt
  - geopandas
  - requests
  - ipykernel
  - astropy-healpix
  - pip
  - pip:
    - PlateTectonicTools
