#####################################
# name of output directories
OutputFiles:
    grd_output_dir: "./data/grid_files/"
    output_gridfile_template: 'M16_seafloor_age_'

TimeParameters:
# --- set parameters
    min_time: 350.
    max_time: 410.
    mor_time_step: 2.
    gridding_time_step: 2.

# Distance in arc-degrees along ridges at which to tessellate lines to
# create seed points
# BUT: does not desample the points where the original line geometries
# are already closer than the specified distance
SpatialParameters:
    ridge_sampling: 0.5
    initial_ocean_healpix_sampling: 32
    initial_ocean_mean_spreading_rate: 75.

    # used to remove small polygons in the masking. Units are area on unit sphere
    area_threshold: 0.0001

    # Control the gridding extent and resolution parameters passed to GMT
    grdspace: 0.5
    xmin: -180.
    xmax: 180.
    ymin: -90.
    ymax: 90.

    grid_masking: True

num_cpus: 1
